package rd.tgic;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(
   modid = "tgic",
   name = "TGIC",
   version = "1.0",
   acceptedMinecraftVersions = "[1.12.2]",
   dependencies = "required-after:techguns;after:incontrol"
)
public class tgicj {
   public static final String MODID = "tgic";
   public static final String NAME = "TechGuns-InControl (TGIC)";
   public static final String VERSION = "1.12.2 (0.1.1)";

   @EventHandler
   public void preInit(FMLPreInitializationEvent event) {
      MinecraftForge.EVENT_BUS.register(new tgice());
      ModMetadata meta = event.getModMetadata();
      meta.autogenerated = false;
      meta.name = "TechGuns-InControl (TGIC)";
      meta.version = "1.12.2 (0.1.1)";
      meta.credits = "sramenradsos";
      meta.description = "Small compatiblity mod for Techguns NPC. \n- Stopping AI range from being reset every tick. \n- Updates Techguns npc combat tasks only when equipment changes, \nAllowing Techguns mobs to properly use any guns with InControl Mod configurations. \n\nRequires Techguns by pWn3d_1337 and InControl by McJty. These mods does not include or redistrubute those files.";
   }
}
